version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - export NODE_OPTIONS=--openssl-legacy-provider
      - npm install

  build:
    commands:
      - npm run build || { echo 'Build failed'; exit 1; }

artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*